# It is gql file for server_manager


type Task{
    taskId: ID!
    taskName: String!
    taskLength: Int!
    communicationCost: Int!
    currentVM: VM
    currentServer: Server
}


type VM{
    vmId: ID!
    vmName: String!
    vmWeight: Int
    vmMips: Int!
    vmCurrentServer: Server
    task: [Task!]
    status: Boolean!
}

type Server{
    serverId: ID!
    serverName: String!
    serverStatus: Boolean!
    serverWeight: Int
    unitPowerCost: Int!
    totalMips: Int!
    usedMips: Int!
    vms: [VM!]
}

input CreateServerInput{
    serverName: String!
    serverStatus: Boolean = false
    serverWeight: Int = 0
    unitPowerCost: Int!
    totalMips: Int!
    usedMips: Int = 0
}

input CreateVMInput{
    vmName: String!
    vmMips: Int!
    vmWeight: Int = 0
    status: Boolean!
}

input CreateTaskInput{
    taskName: String!
    taskLength: Int!
    communicationCost: Int!
}

type Mutation{
    create_server(input: CreateServerInput!): [Server!]!
    create_vm(input: CreateVMInput!): [VM!]!
    create_task(input: CreateTaskInput!): [Task!]!
}

type Query {
      servers: [Server!]!
      vms: [VM!]!
      tasks: [Task!]!
      server(serverId: ID!): Server!
      vm(vmId:ID!): VM!
      task(taskId:ID!): Task!
      serverN(serverName: String!): Server!
      vmN(vmName: String!): VM!
      taskN(taskName: String!): Task!
}